version: '3'
services: 
    db:
        image: 'mongo:4.4.6'
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongoadmin
            MONGO_INITDB_ROOT_PASSWORD: secret
        volumes:
            - /data/db
        ports:
            - "27017:27017"
    app:
        container_name: api-cars
        restart: always
        build: .
        ports:
            - "3000:3000"
        depends_on:
            - db